default_velocity_scaling_vector: 0.1
default_acceleration_scaling_vector:  0.1

joint_limits:
  joint_s: 
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration_limits: 0.0
  joint_l: 
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration_limits: 0.0
  joint_u: 
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration_limits: 0.0
  joint_r: 
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration_limits: 0.0
  joint_b: 
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration_limits: 0.0
  joint_t: 
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration_limits: 0.0