sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: 1
  max_range: 2
  max_update_rate: 10
  padding_offset: 2
  padding_scale: 2
  point_cloud_topic: point_cloud
  point_subsample: 2
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater